/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jack_opencv_myapplication_OpenCVHelper */

#ifndef _Included_com_jack_opencv_myapplication_OpenCVHelper
#define _Included_com_jack_opencv_myapplication_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jack_opencv_myapplication_OpenCVHelper
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_jack_opencv_myapplication_OpenCVHelper_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
